EPS-9: Configure and initialize database
IFortexJavaLab/eps-protchenko-vladislav-java-1 pull request #1
Opened 2024-10-23 12:14 UTC by vladqf

Link to jira ticket: https://ifortex-team-java1.atlassian.net/browse/EPS-9?atlOrigin=eyJpIjoiMzY1NWJiMTQ1MDBlNDM3NGE5Y2UyYzc5NWIxYmI3MzEiLCJwIjoiaiJ9

Set up a database using docker-compose, made a script to create a database schema and fill it with data.

2024-10-23 14:01 UTC, PavelShynkarou requested changes
Looks like your Jira ticket in the wrong state. Please fix it.

2024-10-23 14:01 UTC, PavelShynkarou commented on docker-compose/db-init/V1__initial.sql
> +ORDER BY course_id, student_id;
Did you test it? Does it work properly?

2024-10-24 09:12 UTC, AndreySemeynikovIF approved these changes

2024-10-24 09:13 UTC, AndreySemeynikovIF approved these changes

2024-10-24 09:56 UTC, vladqf commented on docker-compose/docker-compose.yml
> +
Removed all empty lines except one.

2024-10-24 09:56 UTC, vladqf commented on docker-compose/db-init/V1__initial.sql
> +ORDER BY course_id, student_id;
I tested it and it works properly

2024-10-24 09:57 UTC, vladqf commented
> Looks like your Jira ticket in the wrong state. Please fix it.

Fixed

2024-10-24 10:30 UTC, PavelShynkarou approved these changes

2024-10-24 11:33 UTC, AndreySemeynikovIF approved these changes

2024-10-24 11:41 UTC, AndreySemeynikovIF approved these changes

2024-10-24 11:47 UTC, AndreySemeynikovIF approved these changes

2024-10-24 12:29 UTC, PavelShynkarou approved these changes

2024-10-24 15:58 UTC, merged