EPS-19: Set up the project and create entities
IFortexJavaLab/eps-protchenko-vladislav-java-1 pull request #2
Opened 2024-10-29 09:30 UTC by vladqf

- Set up database connection and HikariCP.
- Set up flyway migration.
- Create entities.
- Add several configurations (application-dev.yml, applicaion-prod.yml)

2024-10-29 17:06 UTC, PavelShynkarou requested changes

2024-10-29 17:06 UTC, PavelShynkarou commented on build.gradle
> +    implementation "org.springframework:spring-webmvc:$springWebMvcVersion"
As far as I remember spring-mvc already include core and context dependencies. Could you please recheck it?

2024-10-29 17:06 UTC, PavelShynkarou commented on src/main/java/com/ifortex/internship/model/Course.java
> +public class Course {
Does it necessary use Builder and All/NoArgsConstructors at the same time? From my perspective the better way to use just one approach.

2024-10-29 17:06 UTC, PavelShynkarou commented on src/main/java/com/ifortex/internship/model/Student.java
> +@Builder
the same

2024-10-30 11:43 UTC, vladqf commented on build.gradle
> +    implementation "org.springframework:spring-webmvc:$springWebMvcVersion"
You're right. Removed spring core and spring context dependencies

2024-10-30 11:45 UTC, vladqf commented on src/main/java/com/ifortex/internship/model/Course.java
> +public class Course {
Removed constructor annotations. I'll add them later if necessary

2024-10-30 11:45 UTC, vladqf commented on src/main/java/com/ifortex/internship/model/Student.java
> +@Builder
Also removed constructor annotations.

2024-10-30 11:48 UTC, PavelShynkarou approved these changes

2024-10-31 19:04 UTC, merged