EPS-20: Create a repository layer
IFortexJavaLab/eps-protchenko-vladislav-java-1 pull request #3
Opened 2024-11-05 19:08 UTC by vladqf

- Created StudentRepository and CourseRepository interfaces and their implementations
- Implemented CRUD operations for Course and Student entities
- Provided many-to-many relationship between entities

2024-11-05 20:10 UTC, PavelShynkarou requested changes

2024-11-05 20:10 UTC, PavelShynkarou commented on src/main/java/com/ifortex/internship/repository/impl/JdbcCourseRepository.java
> +    int courseId = jdbcTemplate.queryForObject("SELECT lastval()", Integer.class);
`KeyHolder keyHolder = new GeneratedKeyHolder();

    jdbcTemplate.update(connection -> {
        PreparedStatement ps = connection.prepareStatement(sql, new String[] { "id" });
        ps.setObject(1, entity.getField1());
        ps.setObject(2, entity.getField2());
        return ps;
    }, keyHolder);

    return keyHolder.getKey().longValue();`

2024-11-05 20:10 UTC, PavelShynkarou commented on src/main/java/com/ifortex/internship/repository/StudentRepository.java
> +  Optional<Student> findById(int id);
Could you please provide javaDoc for all methods.

2024-11-05 20:12 UTC, PavelShynkarou commented
Please fix link in PR description in this way - [JIRA-20](https://ifortex-team-java1.atlassian.net/browse/EPS-20)

2024-11-06 08:48 UTC, vladqf commented on src/main/java/com/ifortex/internship/repository/impl/CourseWithStudentExtractor.java
> +package com.ifortex.internship.repository.impl;
Is it really wrong? What package it should be?

2024-11-06 08:54 UTC, PavelShynkarou commented on src/main/java/com/ifortex/internship/repository/impl/CourseWithStudentExtractor.java
> +package com.ifortex.internship.repository.impl;
Why extractor places in implementation package of the repo? The better way to create new package near with impl and put it there

2024-11-06 09:57 UTC, vladqf commented on src/main/java/com/ifortex/internship/repository/CourseRepository.java
> +  Optional<Course> findById(int id);
Done

2024-11-06 09:57 UTC, vladqf commented on src/main/java/com/ifortex/internship/repository/impl/CourseWithStudentExtractor.java
> +import java.util.*;
Done

2024-11-06 09:58 UTC, vladqf commented on src/main/java/com/ifortex/internship/repository/impl/JdbcCourseRepository.java
> +  private final DateTimeFormatter dateTimeFormatter =
You're right. Removed it

2024-11-06 09:58 UTC, vladqf commented on src/main/java/com/ifortex/internship/repository/impl/JdbcCourseRepository.java
> +        SELECT c.id as course_id, c.name as course_name, c.description as course_description,
Done

2024-11-06 09:58 UTC, vladqf commented on src/main/java/com/ifortex/internship/repository/impl/JdbcCourseRepository.java
> +  public void save(Course course) {
Done

2024-11-06 09:59 UTC, vladqf commented on src/main/java/com/ifortex/internship/repository/impl/JdbcCourseRepository.java
> +    Set<Integer> newStudentIds =
There really was logic error. Fixed it

2024-11-06 10:00 UTC, vladqf commented on src/main/java/com/ifortex/internship/repository/impl/CourseWithStudentExtractor.java
> +package com.ifortex.internship.repository.impl;
Fixed it

2024-11-06 10:01 UTC, vladqf commented on src/main/java/com/ifortex/internship/repository/impl/JdbcStudentRepository.java
> +  public void save(Student student) {
Done

2024-11-06 10:01 UTC, vladqf commented on src/main/java/com/ifortex/internship/repository/impl/JdbcCourseRepository.java
> +    int courseId = jdbcTemplate.queryForObject("SELECT lastval()", Integer.class);
Done

2024-11-06 10:01 UTC, vladqf commented on src/main/java/com/ifortex/internship/repository/StudentRepository.java
> +  Optional<Student> findById(int id);
Done

2024-11-06 13:23 UTC, AndreySemeynikovIF commented on src/main/java/com/ifortex/internship/repository/impl/JdbcCourseRepository.java
> +  private void updateCourseStudents(int courseId, Set<Integer> newStudentIds) {
Each course update request will have to include a list of all enrolled students, right?
If I suddenly forget to add an already enrolled student to the list, will he be removed from the course? If I pass an empty list of students during the course update, will everyone be deleted?
Is it possible in this case to implement a partial update so that I can update, for example, only the description?

2024-11-06 15:46 UTC, PavelShynkarou requested changes

2024-11-06 15:46 UTC, PavelShynkarou commented on src/main/java/com/ifortex/internship/repository/impl/JdbcCourseRepository.java
> +    String sql =
discussed.

2024-11-09 21:49 UTC, vladqf commented on src/main/java/com/ifortex/internship/repository/impl/JdbcCourseRepository.java
> +  private void updateCourseStudents(int courseId, Set<Integer> newStudentIds) {
Made a little changes: added partial update, simplified update course-students logic and moved it to the separate method. In my implementation, if dto contains a student list, all previous students will be replaced with new, otherwise, everything stays as it is. So, if you pass an empty list during the course update, all the students will be removed from the course.

2024-11-09 21:50 UTC, vladqf commented on src/main/java/com/ifortex/internship/repository/CourseRepository.java
> +  Optional<Course> findById(int id);
Fixed

2024-11-09 21:51 UTC, vladqf commented on src/main/java/com/ifortex/internship/repository/StudentRepository.java
> +  Optional<Student> findById(int id);
Added link to Student class

2024-11-10 07:06 UTC, PavelShynkarou approved these changes

2024-11-10 09:59 UTC, AndreySemeynikovIF approved these changes

2024-11-10 12:05 UTC, merged