EPS-10: Implement CRUD operations
IFortexJavaLab/eps-protchenko-vladislav-java-1 pull request #4
Opened 2024-11-13 14:38 UTC by vladqf

- Created StudentService and CourseService interfaces and their implementations,
- Implemented CRUD operations for Course and Student entities,
- Created DTOs and validators for each DTO,
- Added custom exceptions
- Added scheduler that checks and changes course status if necessary once a day

Link to JIRA ticket: https://ifortex-team-java1.atlassian.net/browse/EPS-10

2024-11-13 18:36 UTC, PavelShynkarou requested changes
Please to description of the PR provide correct formatting to Jira ticket and put ticket to correct status!

2024-11-13 18:36 UTC, PavelShynkarou commented on src/main/java/com/ifortex/internship/service/impl/CourseServiceImpl.java
> +  public CourseDto deleteCourse(long id) {
Why delete returns Entity? We decided to return entity only for POST/PUT methods, and we had conversation we clarify it one more time. Let's make it void.

2024-11-13 18:36 UTC, PavelShynkarou commented on src/main/java/com/ifortex/internship/service/impl/StudentServiceImpl.java
> +  public StudentDto deleteStudent(long id) {
the same

2024-11-13 18:36 UTC, PavelShynkarou commented on src/main/java/com/ifortex/internship/service/util/CourseUtil.java
> +    private final TechnicalRepository repository;
looks like formatting lost here

2024-11-13 18:36 UTC, PavelShynkarou commented on src/main/java/com/ifortex/internship/service/validator/CourseDtoValidator.java
> +    if (!startDate.isAfter(LocalDate.now()) && !oldIsOpen && newIsOpen) {
boolean courseAlreadyStarted = !startDate.isAfter(LocalDate.now());
    boolean isOpeningClosedCourse = !oldIsOpen && newIsOpen;
    boolean invalidStatusChange = courseAlreadyStarted && isOpeningClosedCourse;

    if (invalidStatusChange) {
        throw new CourseHasAlreadyStartedException("Course has already started. Cannot change status.");
    }

2024-11-13 18:36 UTC, PavelShynkarou commented on src/main/java/com/ifortex/internship/service/validator/CourseDtoValidator.java
> +    if (courseDto.getStudents() == null) {
Just a question Course can't be created without students?

2024-11-13 18:36 UTC, PavelShynkarou commented on src/main/java/com/ifortex/internship/service/validator/StudentDtoValidator.java
> +        && !name.isBlank()
`
  boolean isNameProvided = name != null && !name.isBlank();
  boolean isNameLengthValid = name != null && name.length() >= MIN_NAME_LENGTH && name.length() <= MAX_NAME_LENGTH;
  boolean isNameValid = isNameProvided && isNameLengthValid
 `

2024-11-13 18:36 UTC, PavelShynkarou commented on src/main/java/com/ifortex/internship/service/validator/CourseDtoValidator.java
> +  private void validateName(String name) {
Lets put private methods after public

2024-11-14 08:50 UTC, vladqf commented on src/main/java/com/ifortex/internship/repository/util/TechnicalRepository.java
> +@Component
done

2024-11-14 08:50 UTC, vladqf commented on src/main/java/com/ifortex/internship/exception/CourseHasAlreadyStartedException.java
> +    super(message);
done

2024-11-14 08:50 UTC, vladqf commented on src/main/java/com/ifortex/internship/service/enums/CourseField.java
> +public enum CourseField {
done

2024-11-14 08:50 UTC, vladqf commented on src/main/java/com/ifortex/internship/service/impl/StudentServiceImpl.java
> +  public StudentDto deleteStudent(long id) {
also fixed

2024-11-14 08:51 UTC, vladqf commented on src/main/java/com/ifortex/internship/service/util/CourseUtil.java
> +    private final TechnicalRepository repository;
fixed formatting

2024-11-14 08:51 UTC, vladqf commented on src/main/java/com/ifortex/internship/service/validator/CourseDtoValidator.java
> +    if (!startDate.isAfter(LocalDate.now()) && !oldIsOpen && newIsOpen) {
done

2024-11-14 08:51 UTC, vladqf commented on src/main/java/com/ifortex/internship/service/validator/StudentDtoValidator.java
> +        && !name.isBlank()
done

2024-11-14 08:51 UTC, vladqf commented on src/main/java/com/ifortex/internship/service/validator/CourseDtoValidator.java
> +  private void validateName(String name) {
done

2024-11-14 09:31 UTC, PavelShynkarou commented on src/main/java/com/ifortex/internship/service/validator/CourseDtoValidator.java
> +    if (courseDto.getStudents() == null) {
It is strange. Lets put this check to check below where you a re checking the length of students list, if it is not null and length check after. Looks like it will works

2024-11-14 16:36 UTC, vladqf commented on src/main/java/com/ifortex/internship/service/validator/StudentDtoValidator.java
> +        && !name.isBlank()
fixed this

2024-11-15 08:51 UTC, AndreySemeynikovIF commented on src/main/java/com/ifortex/internship/dto/CourseDto.java
> +  private LocalDateTime lastUpdateDate;
User not given the time of last change?

2024-11-15 08:51 UTC, AndreySemeynikovIF commented on src/main/java/com/ifortex/internship/service/impl/CourseServiceImpl.java
> +                    new EntityNotFoundException(String.format("Course with id %s not found", id))));
Do you provide custom error code with exception?

2024-11-15 08:51 UTC, AndreySemeynikovIF commented on src/main/resources/db/migration/V1__initial.sql
> +
Should we provide logic to close courses after their finishing? Like startDate + duartion = currentDate -> course closed?

2024-11-15 09:55 UTC, vladqf commented on src/main/java/com/ifortex/internship/service/impl/CourseServiceImpl.java
> +                    new EntityNotFoundException(String.format("Course with id %s not found", id))));
Do we need to provide it here?

2024-11-15 10:11 UTC, vladqf commented on src/main/java/com/ifortex/internship/dto/CourseDto.java
> +  private LocalDateTime lastUpdateDate;
That wasn't supposed) Already fixed

2024-11-15 10:25 UTC, AndreySemeynikovIF commented on src/main/java/com/ifortex/internship/service/impl/CourseServiceImpl.java
> +                    new EntityNotFoundException(String.format("Course with id %s not found", id))));
Can agree. Exception handler will be implemented in the next task?

2024-11-15 10:28 UTC, AndreySemeynikovIF approved these changes

2024-11-15 11:29 UTC, vladqf commented on src/main/java/com/ifortex/internship/service/impl/CourseServiceImpl.java
> +                    new EntityNotFoundException(String.format("Course with id %s not found", id))));
ControllerAdvice will be implemented within RestAPI task

2024-11-15 16:30 UTC, AndreySemeynikovIF approved these changes

2024-11-15 16:31 UTC, AndreySemeynikovIF approved these changes

2024-11-15 16:37 UTC, merged