EPS-11: Implement search and sorting logic
IFortexJavaLab/eps-protchenko-vladislav-java-1 pull request #5
Opened 2024-11-17 16:32 UTC by vladqf

[JIRA-11](https://ifortex-team-java1.atlassian.net/browse/EPS-11)
- Added search and sorting capability,
- Fixed issue with passing non-existing student IDs and name validation during course create/update.

2024-11-17 17:14 UTC, PavelShynkarou requested changes

2024-11-17 17:14 UTC, PavelShynkarou commented on src/main/java/com/ifortex/internship/repository/impl/JdbcCourseRepository.java
> +    String sql = "SELECT * FROM students WHERE id IN (:studentIds)";
As far as I can see the main reason to provide new Jdbc bean is list ids usaging? But from my perspective it still can be implemented with jdbcTemplate itself. Lets support one style of querying.

2024-11-17 17:14 UTC, PavelShynkarou commented on src/main/java/com/ifortex/internship/repository/impl/JdbcCourseRepository.java
> +      if (hasSort) {
` sqlBuilder.append(hasSort ? ", " : " ORDER BY ")
              .append("c.name ")
              .append(dto.getSortByName().name().toUpperCase());`

2024-11-17 17:53 UTC, vladqf commented on src/main/java/com/ifortex/internship/repository/impl/JdbcCourseRepository.java
> +    String sql = "SELECT * FROM students WHERE id IN (:studentIds)";
This is how it'll look like:
StringBuilder sqlBuilder = new StringBuilder("SELECT * FROM students WHERE id IN (");
    sqlBuilder.append(String.join(", ", studentIds.stream().map(Object::toString).toList()));
    sqlBuilder.append(")");
    
Not sure, which approach is better

2024-11-17 18:14 UTC, vladqf commented on src/main/java/com/ifortex/internship/dto/FilterSortDto.java
> +
Fixed

2024-11-17 18:16 UTC, vladqf commented on src/main/java/com/ifortex/internship/repository/CourseRepository.java
> +   * Retrieves courses based on applied filters and sorting criteria.
fixed

2024-11-17 18:16 UTC, vladqf commented on src/main/java/com/ifortex/internship/repository/CourseRepository.java
> +   * Updates the students associated with a specific course based on new and existing student IDs.
Done

2024-11-17 18:16 UTC, vladqf commented on src/main/java/com/ifortex/internship/repository/impl/JdbcCourseRepository.java
> +      if (hasSort) {
Done

2024-11-17 18:50 UTC, PavelShynkarou commented on src/main/java/com/ifortex/internship/repository/impl/JdbcCourseRepository.java
> +    String sql = "SELECT * FROM students WHERE id IN (:studentIds)";
What if something in this way ?
    String placeholders = studentIds.stream()
                                    .map(id -> "?")
                                    .collect(Collectors.joining(",", "(", ")"));

    String sql = "SELECT * FROM students WHERE id IN " + placeholders;
    return jdbcTemplate.query(sql, studentIds.toArray(), (rs, rowNum) -> 
        new Student(
            rs.getLong("id"),
            rs.getString("name")
        )
    );

2024-11-18 07:17 UTC, vladqf commented on src/main/java/com/ifortex/internship/repository/impl/JdbcCourseRepository.java
> +    String sql = "SELECT * FROM students WHERE id IN (:studentIds)";
Do we need to map id to "?" ? We can do smth like this:
![image](https://github.com/user-attachments/assets/b871da3d-77e8-41d9-99bd-ce1fb1308898)

2024-11-18 07:47 UTC, PavelShynkarou commented on src/main/java/com/ifortex/internship/repository/impl/JdbcCourseRepository.java
> +    String sql = "SELECT * FROM students WHERE id IN (:studentIds)";
You gonna substitute ids themself directly without prevent SQL injection and ignore SQL standarts ?

2024-11-18 10:32 UTC, vladqf commented on src/main/java/com/ifortex/internship/repository/impl/JdbcCourseRepository.java
> +    String sql = "SELECT * FROM students WHERE id IN (:studentIds)";
Are there any injections possible? If so, your version will be better

2024-11-18 11:05 UTC, vladqf commented on src/main/java/com/ifortex/internship/repository/impl/JdbcCourseRepository.java
> +    String sql = "SELECT * FROM students WHERE id IN (:studentIds)";
Done

2024-11-18 11:32 UTC, PavelShynkarou approved these changes

2024-11-18 12:58 UTC, AndreySemeynikovIF approved these changes

2024-11-18 13:00 UTC, merged